# --- PERFIL DE DESENVOLVIMENTO (dev) ---

# Conexão com o banco
spring.datasource.url=


# Configurações JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
