GET http://localhost:8080/produtos

### Buscar produtos por nome
GET http://localhost:8080/produtos/buscanome?nome=bloco

### Buscar produtos por referência
GET http://localhost:8080/produtos/buscaref?referencia=61211

### Buscar produto por código de sistema
GET http://localhost:8080/produtos/buscacod?codigo=0000136

### Buscar produto por código de barras
GET http://localhost:8080/produtos/buscaean?codigoBarras=7898059541123